# Generated by Django 3.0.3 on 2020-03-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_orderitem_price_in_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_in_cart',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
