# Generated by Django 3.0.3 on 2020-04-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='creditCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('card_number', models.CharField(max_length=20)),
                ('expDate', models.CharField(max_length=5)),
                ('cardType', models.CharField(max_length=15)),
                ('cvv', models.CharField(max_length=3)),
                ('Username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='shippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('zipCode', models.CharField(max_length=5)),
                ('Username', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='Address',
            field=models.CharField(default='dafault address', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Email',
            field=models.CharField(default='default email', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Username',
            field=models.CharField(default='default username', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='default name', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='nickName',
            field=models.CharField(default='default nickname', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='0000', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(default='1234567890', max_length=10),
            preserve_default=False,
        ),
    ]
