# Generated by Django 3.0.3 on 2020-04-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_details', '0001_initial'),
    ]

    operations = [
    ]
