# Generated by Django 3.0.3 on 2020-03-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('image', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
    ]
