# Generated by Django 3.0.3 on 2020-04-10 22:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=120)),
                ('authorBio', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=1000)),
                ('genre', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=1000)),
                ('coverImage', models.ImageField(upload_to='images/')),
                ('releasedDate', models.DateField(default=datetime.datetime(2020, 4, 10, 22, 10, 36, 628008, tzinfo=utc))),
                ('authorInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.authors')),
            ],
        ),
    ]
