# Generated by Django 3.0.3 on 2020-03-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=1000)),
                ('genre', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=1000)),
                ('coverImage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
