# Generated by Django 3.0.3 on 2020-04-10 22:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='releasedDate',
            field=models.DateField(default=datetime.datetime(2020, 4, 10, 22, 38, 2, 422668, tzinfo=utc)),
        ),
    ]
