# Generated by Django 3.0.3 on 2020-03-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200301_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to=''),
        ),
    ]
