# Generated by Django 3.0.3 on 2020-03-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_books_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='authorBio',
            field=models.CharField(default='place holder', max_length=1000),
        ),
    ]
