# Generated by Django 3.0.3 on 2020-03-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_books_authorbio'),
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=120)),
                ('authorBio', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='authorBio',
        ),
    ]
