# Generated by Django 3.0.3 on 2020-03-25 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200325_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='authorInfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.authors'),
            preserve_default=False,
        ),
    ]
