# Generated by Django 3.0.3 on 2020-04-03 02:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_books_authorinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='releaseDate',
            field=models.DateField(default=datetime.datetime(2020, 4, 3, 2, 7, 21, 676102, tzinfo=utc)),
        ),
    ]
