# Generated by Django 3.0.3 on 2020-02-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
    ]
