# Generated by Django 3.0.3 on 2020-02-20 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_author'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
